EPMSEnrollmentApplication/Controllers/ScreeningController.cs
using EPMSEnrollmentApplication.Helpers;
using EPMSEnrollmentApplication.Models;
using PassportApplicationCommon.Models;
using PassportApplicationProxy;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Address = PassportApplicationCommon.Models.Address;

namespace EPMSEnrollmentApplication.Controllers
{
    [UserAuthorized]
    public class ScreeningController : Controller
    {
        #region Actions

        public ActionResult Index(string msg)
        {
            var model = new PassportSearch();

            // Get all uncompleted applications
            ViewData["Enrollments"] = new CommonHelper().SelectCompletedEnrollments();

            // Set viewable options            
            model.CompletedType = 2;

            // If there is a message, show it
            ViewBag.Msg = msg;

            return View(model);
        }

        public ActionResult ViewApplicationScreening()
        {
            ViewBag.ShowScreeningMenuOptions = 1;
            ViewBag.ShowScreeningSubMenuOptions = 1;

            // Set Model
            var model = Session["CurrentApplication"] as PassportApplication;

            // Update payment details
            new PaymentProxy().PaymentChannel.CheckPaymentDetails(ref model);

            //// Previous Passports
            //ViewData["PreviousPassports"] = new LookupProxy().LookupChannel.GetPreviousPassports("PassportNumber");

            // Set breeder docs
            if (model.PassportInformation.ApplicationType != 0)
            {
                var breederDocs = GetPassportBreederDocs(model.PassportInformation.ApplicationType);

                foreach (var doc in breederDocs)
                {
                    if (model.BreederDocs.Where(x => x.DocumentId == doc.DocumentId).FirstOrDefault() != null)
                    {
                        doc.IsVerified = true;
                    }
                }

                model.BreederDocs = breederDocs;
            }

            // Reject reasons
            ViewData["RejectionReasons"] = new CommonHelper().SelectRejectReasons();

            if (!string.IsNullOrEmpty(model.PassportInformation.PreviousPassportNumber))
            {
                // Previous passports
                model.PreviousPassports = GetPreviousPassportsDetails(model.PassportInformation.PreviousPassportNumber);
            }

            return View("_ScreeningSummary", model);
        }

        #endregion

        #region Json

        public ActionResult RejectPassport(string formno, string reasonid, string reason)
        {
            if (!string.IsNullOrEmpty(formno) && !string.IsNullOrEmpty(reasonid) && !string.IsNullOrEmpty(reason))
            {
                new EnrollmentProxy().EnrollmentChannel.RejectEnrollment(formno, reasonid, reason);
                return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AcceptPassport(string formno)
        {
            if (!string.IsNullOrEmpty(formno))
            {
                new EnrollmentProxy().EnrollmentChannel.AcceptEnrollment(formno);
                return Json(new { status = 1 }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { status = 0 }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult PassportImage(string passportNo, bool isFaceImage)
        {
            var passportImage = new LookupProxy().LookupChannel.GetPassportImage(passportNo, isFaceImage);

            if (passportImage != null)
            {
                return File(passportImage, "image/jpg");
            }
            return File(HttpContext.Server.MapPath("~/Content/Images/EmptySignatureImage.jpg"), "image/jpg");
        }

        #endregion

        #region Operations

        private static List<Passport> GetPreviousPassportsDetails(string passportnum)
        {
            if (!string.IsNullOrEmpty(passportnum))
            {
                // var message = string.Empty;

                if (!new CommonHelper().ValidPassportNo(passportnum))
                {
                    // message = "Please check the passport number. It needs to be 9 characters long, start with an A,D or F followed by 8 numbers.";
                }
                
                passportnum = passportnum.ToUpper();

                // Search Passport
                var passportsVerified = new LookupProxy().LookupChannel.GetPassportHistory(passportnum);

                var passportVerified = passportsVerified.SingleOrDefault(c => c.DocNo == passportnum);

                if (passportVerified?.IssueDate.AddYears(5) < DateTime.Now)
                {
                    if (passportVerified.StageCode == "EM5000")
                    {
                        passportVerified.StageCode = "0";
                        passportVerified.StageDescription = "EXPIRED";
                    }
                    else
                    {
                        passportVerified.StageCode = "0";
                        passportVerified.StageDescription += " / EXPIRED";
                    }
                }

                // order by time
                passportsVerified = passportsVerified.OrderByDescending(x => x.IssueDate).ToList();

                // put original in front
                passportsVerified = passportsVerified.OrderByDescending(x => x.DocNo == passportnum).ToList();

                return passportsVerified;
            }

            return null;
        }       

        private PassportApplication GetTempData()
        {
            var model = new PassportApplication
            {
                PassportInformation = new PassportInformation()
                {
                    ApplicationType = 1,
                    DocumentType = 1
                },
                Payment = new PaymentInformation()
                {
                    ApplicationId = 9080032,
                    ReferenceNumber = 1543187815,
                    Firstname = "ABOSEDE",
                    Surname = "ABIJO",
                    DateOfBirth = DateTime.Parse("10-Jun-49"),
                    Gender = "F",
                    PayeAmount = 8950,
                    PayeDatepaid = DateTime.Parse("20-Apr-2015"),
                    PaymentExist = true,
                    PaymentMatch = true,
                    FirstnameMatch = true,
                    SurnameMatch = true,
                    CalculatedBasePrice = 8750,
                    CalculatedAdditionalPrice = 0,
                    PaymentTotalPrice = 8750
                },
                PersonalInformation = new PersonalInformation()
                {
                    Firstname = "ABOSEDE",
                    Surname = "ABIJO",
                    DateOfBirth = DateTime.Parse("10-Jun-49"),
                    Gender = "F",
                    MaritialStatus = 1,
                }
            };

            model.PersonalInformation.MaritialStatus = 1;

            model.ContactDetails = new ContactDetails()
            {
                MobilePhoneNumber = "08094562884",
                Address = new Address()
                {
                    AddressLine1 = "14 Ado Ekiti Road",
                    City = "Kaduna",
                    Country = "Nigeria",
                    State = "Kaduna",
                    Lga = "KadoEkiti"
                }
            };

            model.Locality = new Locality()
            {
                PlaceOfBirth = "Kaduna",
                StateOfOrigin = "Abia",
                HomeTown = "Kado",
                Nationality = "Nigeria"
            };

            model.PersonalFeatures = new PersonalFeatures()
            {
                ColourOfEyes = 1,
                ColourOfHair = 2,
                HeightInCm = 182
            };

            model.NextOfKin = new NextOfKin()
            {
                NextOfKinName = "Johnson Bado",
                ContactNumberOfNextOfKin = "08093345667",
                RelationshipWithNextOfKin = "Brother",
                Address = new Address()
                {
                    AddressLine1 = "14 Ado Ekiti Road",
                    City = "Kaduna",
                    Country = "Nigeria",
                    State = "Kaduna",
                    Lga = "KadoEkiti"
                }
            };

            return model;
        }

        private List<BreederDoc> GetPassportBreederDocs(int applicationType)
        {
            return new LookupProxy().LookupChannel.GetApplicationTypeDocuments(applicationType);
        }

        public string JsonPartialView(Controller controller, string viewName, object model)
        {
            controller.ViewData.Model = model;

            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(controller.ControllerContext, viewName);
                var viewContext = new ViewContext(controller.ControllerContext, viewResult.View, controller.ViewData, controller.TempData, sw);

                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(controller.ControllerContext, viewResult.View);

                return sw.ToString();
            }
        }

        #endregion
    }
}

EPMSEnrollmentApplication/Views/Screening/Index.cshtml
@model EPMSEnrollmentApplication.Models.PassportSearch

<link rel="stylesheet" type="text/css" href="/content/page.css" />
<link rel="stylesheet" type="text/css" href="/content/inputs.css" />
<link rel="stylesheet" type="text/css" href="/content/screening.css">

<div id="EnrolementDiv">
    <div id="passportdetails" class="formdiv spacedownm">@(Html.Partial("../Enrollment/SearchEnrollment", Model))</div>
    <div id="searchResultdiv" class="hidden"></div>
    <div id="PopupMsg" class="PopupWindow">
        <div class="closebtn">X</div>
        <div id="popupmsgInner" class="popupinfoinner bigfirstletter"></div>
    </div>

    <div id="RejectMsg" class="PopupWindow">
        <div>Please give a reason for rejecting this application:</div>
        <textarea id="rejectreason" class="spacedownm"></textarea>
        <div id="cancelrejectbtn" class="genbutton closeme left">Cancel</div>
        <div id="rejectappbtn" class="genbutton red right rejectbtn">Reject</div>
        <div class="clear"></div>
    </div>
</div>

<script src="/scripts/jquery.validate.js" type="text/javascript"></script>
<script src="/scripts/jquery.validate-vsdoc.js" type="text/javascript"></script>
<script src="/scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
<script src="/scripts/screening.js" type="text/javascript"></script>
<script src="/scripts/jquery-ui.js" type="text/javascript"></script>
<script type="text/javascript" src="~/Scripts/jquery.lightbox_me.js"></script>

@if (ViewBag.Msg == "1")
{
    <script type="text/javascript">
        $(function () {
            var msg = "Application Accepted";

            $('#popupmsgInner').html(msg);
            $('#PopupMsg').lightbox_me({
                centered: true
            });
        })
    </script>
}

@if (ViewBag.Msg == "2")
{
    <script type="text/javascript">
        $(function () {
            var msg = "Application Rejected";

            $('#popupmsgInner').html(msg);
            $('#PopupMsg').lightbox_me({
                centered: true
            });
        })
    </script>
}

EPMSEnrollmentApplication/Views/Screening/MenuOptions.cshtml
<div><a href="/ApplicationScreening" class="option shadow">Application Screening</a></div>

EPMSEnrollmentApplication/Views/Screening/MenuSubOptions.cshtml
<div id="screeningSuboptions" class="shadow">
    <div id="searchResultoptionsdiv" class="spacedown">
        <div class="divheader2 padded">Screening Steps</div>
        <div class="linkoption active spacetopm5">Enrollment</div>
        <div class="linkoptionsubheader" id="passportdetailslink">Passport Information</div>
        <div class="linkoptionsubheader" id="paymentinfolink">Payment</div>
        <div class="linkoptionsubheader" id="personaldetailslink">Personal Information</div>
        <div class="linkoptionsubheader" id="contactdetailslink">Contact Details</div>
        <div class="linkoptionsubheader" id="localitylink">Locality</div>
        <div class="linkoptionsubheader" id="personalfeatureslink">Personal Features</div>
        <div class="linkoptionsubheader" id="nokinfolink">Next Of Kin</div>

        <div class="linkoption active">Screening</div>
        <div class="linkoptionsubheader" id="historicreportslink">Historic Reports</div>
        <div class="linkoptionsubheader" id="breederdocslink">Breeder Documents</div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_BreederDocuments.cshtml
@model List<PassportApplicationCommon.Models.BreederDoc>
<div class="spaced">
    <div class="leftside shadow">
        <div class="divheader">Breeder Documents Required</div>
        <div class="grayleftborder padded spaceleftx2 spacetopx2">
            @if (Model.Count == 0)
            {
                <div class="spacedown">Select a passport application type</div>
            }
            else
            {
                for (var i = 0; i < Model.Count; i++)
                {
                    <div>
                        <div class="spacedown inline">@Html.CheckBoxFor(m => Model[i].IsVerified, new { disabled = "disabled" })</div>
                        @Html.Hidden("DocumentId", Model[i].DocumentId, new { @class = "docid" })
                        <div class="inline sub">@Model[i].DocumentName</div>
                    </div>
                }
            }
        </div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_ContactDetailsScreening.cshtml
@model PassportApplicationCommon.Models.ContactDetails

<div class="spaced">
    <div class="leftside shadow">
        <div class="divheader">Contact Information</div>

        <div class="grayleftborder">
            <table>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.ContactPhoneNumber)
                    </th>
                    <td>
                        <div class="labeltxt">@(string.IsNullOrEmpty(Model.ContactPhoneNumber) ? "--" : Model.ContactPhoneNumber)</div>
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.EmailAddress)
                    </th>
                    <td>
                        <div class="labeltxt">@(string.IsNullOrEmpty(Model.EmailAddress) ? "--" : Model.EmailAddress)</div>
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.MobilePhoneNumber)
                    </th>
                    <td>
                        <div class="labeltxt">@(string.IsNullOrEmpty(Model.MobilePhoneNumber) ? "--" : Model.MobilePhoneNumber)</div>
                    </td>
                </tr>
            </table>
            @Html.Partial("../Screening/_ScreeningAddress", Model.Address)
        </div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_HistoricPassports.cshtml
@using PassportApplicationCommon.Models
@model List<Passport>

<div class="spaced">
    <div class="leftside shadow">
        <div class="divheader">Historic Passports</div>
        <div class="grayleftborder paddednotop spaceleftx2 whitebg">
        @if (Model == null || Model.Count == 0)
        {
            <div class="nomsg">No history available for this passport application</div>
        }
        else
        { 
            <table>
                <tr>
                    <td>
                        The first document is the one that was searched for. <br />The other passports belonging to this entity is arranged by issue date.
                    </td>
                </tr>
                <tr>
                    <td class="passportlist">
                        @Html.Partial("_PassportCompareheaders")
                        @foreach (var pPort in Model)
                        {
                            @Html.Partial("_PassportCompareColumn", pPort)
                        }
                    </td>
                </tr>
            </table>
        }
        </div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_NextOfKinDetailsScreening.cshtml
@model PassportApplicationCommon.Models.NextOfKin

<div class="spaced">
    <div class="leftside shadow">
        <div class="divheader">Next of Kin Information</div>

        <div class="grayleftborder spaceleft">
            <table>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.NextOfKinName)
                    </th>
                    <td>
                        <div class="labeltxt capitalize">@Model.NextOfKinName.ToLower()</div>
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.RelationshipWithNextOfKin)
                    </th>
                    <td>
                        <div class="labeltxt capitalize">@Model.RelationshipWithNextOfKin.ToLower()</div>
                    </td>
                </tr>
                <tr>
                    <th>
                        @Html.LabelFor(model => Model.ContactNumberOfNextOfKin)
                    </th>
                    <td>
                        <div class="labeltxt">@Model.ContactNumberOfNextOfKin</div>
                    </td>
                </tr>
            </table>

            @Html.Partial("../Screening/_ScreeningAddress", Model.Address)
        </div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_PassportCompareColumn.cshtml
@model PassportApplicationCommon.Models.Passport

    <table class="CompareList">                                
        <tr>                         
            <td>
                <b>@Model.DocNo</b>
            </td>
        </tr>      
        <tr>                                    
            <td>
                @if (@Model.DocType == "DIPLOMATIC PASSPORT")
                {
                    <span class="gray stagecode">@Model.DocType</span>
                }
                else if (@Model.DocType == "OFFICIAL PASSPORT")
                {
                    <span class="maroon stagecode">@Model.DocType</span>
                }
                else
                {
                    <span class="blue stagecode">@Model.DocType</span>
                }
                
            </td>
        </tr>                
        <tr>                          
            <td>
                @Model.IssueDate.ToString("dd/MM/yyyy")
            </td>
        </tr>
        <tr>
            <td style="height:250px;">
                <img src="@Url.Action("PassportImage", "Screening", new { passportNo = Model.DocNo, isFaceImage = true })" width="100%" height="auto" />        
                @*<img src="~/Content/Images/DummyData/Face.JPG" width="100%" height="auto"/>*@
                <div class="ppimg" style="background-image: url()"
            </td>
        </tr>
        <tr>
            <td style="height:40px; line-height: 40px;">           
                <img src="@Url.Action("PassportImage", "Screening", new { passportNo = Model.DocNo, isFaceImage = false })" width="100%" , height="auto" />                      
                @*<img src="~/Content/Images/DummyData/Signature.JPG" width="100%" height="auto" />*@
            </td>
        </tr>                          
        <tr>                            
            <td>
                @Model.ExpiryDate.ToString("dd/MM/yyyy")
            </td>
        </tr>   
        <tr>                            
            <td>
                @Model.IssuePlace
            </td>
        </tr>
   
        <tr>                         
            <td>
                @Model.Surname        
            </td>
        </tr>
        <tr>                            
            <td>
                @Model.FirstName        
            </td>
        </tr>
        <tr>                            
            <td>
                @Model.OtherNames&nbsp       
            </td>
        </tr>
        <tr>                            
            <td>
                @Model.GenderDesc        
            </td>
        </tr>
        <tr>                            
            <td>                                
                @Model.BirthDate.ToString("dd/MM/yyyy")
            </td>
        </tr>
         <tr>                            
            <td>
                @if (Model.StageCode == "EM5000" || Model.StageCode == "PM2000")
                {
                    <span class="green stagecode">@Model.StageDescription</span>
                }
                else
                {
                    <span class="red stagecode">@Model.StageDescription</span>
                }                              
            </td>
        </tr>
        <tr>
            <td>
                @*Html.ActionLink("Print", "PassportValidation", "Report", new { docNo =@Model.DocNo, surname = @Model.Surname, firstName = @Model.FirstName, gender = @Model.Gender, birthDate = @Model.BirthDate, stageDescription = @Model.StageDescription, historyID = @Model.HistoryID, otherNames = @Model.OtherNames, issueDate = @Model.IssueDate, expiryDate = @Model.ExpiryDate, docType = @Model.DocType, issuePlace = @Model.IssuePlace }, new { target = "_blank" })*@        
            </td>
        </tr>
    </table>

EPMSEnrollmentApplication/Views/Screening/_PassportCompareHeaders.cshtml
<table class="rightspace passportlistheaders">
    <tr>
        <td>
            Passport Number
        </td>
    </tr>
    <tr>
        <td>
            Document Type
        </td>
    </tr>
    <tr>
        <td>
            Date of Issue
        </td>
    </tr>
    <tr>
        <td style="height:250px; line-height: 250px;">
            Photo
        </td>
    </tr>
    <tr>
        <td style="height:40px; line-height: 40px;">
            Signature
        </td>
    </tr>
    <tr>
        <td>
            Expiry Date
        </td>
    </tr>
    <tr>
        <td>
            Issue Place
        </td>
    </tr>
    <tr>
        <td>
            Surname
        </td>
    </tr>
    <tr>
        <td>
            First Name
        </td>
    </tr>
    <tr>
        <td>
            Other Names
        </td>
    </tr>
    <tr>
        <td>
            Gender
        </td>
    </tr>
    <tr>
        <td>
            Date of Birth
        </td>
    </tr>
    <tr>
        <td style="height:40px">
            Document Status
        </td>
    </tr>
    <tr>
        <td>
            &nbsp
        </td>
    </tr>
</table>

EPMSEnrollmentApplication/Views/Screening/_PaymentDetailScreening.cshtml
@model PassportApplicationCommon.Models.PaymentInformation

<div class="spaced">
    <div class="leftside shadow">
        <div class="divheader">Enroll Payment Information</div>

        @using (@Html.BeginForm())
        {
            <div class="grayleftborder">
                <table>
                    <tr>
                        <th>
                            Application ID
                        </th>
                        <td>
                            <div class="labeltxt">@Model.ApplicationId</div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.LabelFor(model => Model.ReferenceNumber)
                        </th>
                        <td>
                            <div class="labeltxt">@Model.ReferenceNumber</div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            First Name
                        </th>
                        <td>
                            <div class="labeltxt capitalize">@Model.Firstname.ToLower()</div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            Surname
                        </th>
                        <td>
                            <div class="labeltxt capitalize">@Model.Surname.ToLower()</div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.LabelFor(model => Model.DateOfBirth)
                        </th>
                        <td>
                            <div class="labeltxt">@(Model.DateOfBirth == DateTime.MinValue ? "" : Model.DateOfBirth.ToString("dd/MMM/yyyy"))</div>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @Html.LabelFor(model => Model.Gender)
                        </th>
                        <td>
                            <div class="labeltxt">@(Model.Gender == "M" ? "Male" : "Female")</div>
                        </td>
                    </tr>
                </table>
            </div>
        }

        <div id="PaymentValidationDiv">
            @Html.Partial("../Screening/_PaymentProcessScreening", Model)
        </div>
    </div>
</div>

EPMSEnrollmentApplication/Views/Screening/_ScreeningAddress.cshtml
@model PassportApplicationCommon.Models.Address

<table>
    <tr>
        <th>
            @Html.LabelFor(model => model.AddressLine1)
        </th>
        <td>
            <div class="labeltxt">@Model.AddressLine1</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.AddressLine2)
        </th>
        <td>
            <div class="labeltxt">@(string.IsNullOrEmpty(Model.AddressLine2) ? "--" : Model.AddressLine2)</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.PostalCode)
        </th>
        <td>
            <div class="labeltxt">@(string.IsNullOrEmpty(Model.PostalCode) ? "--" : Model.PostalCode)</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.City)
        </th>
        <td>
            <div class="labeltxt capitalize">@Model.City.ToLower()</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.District)
        </th>
        <td>
            <div class="labeltxt capitalize">@(string.IsNullOrEmpty(Model.District) ? "--" : Model.District.ToLower())</div>
        </td>
    </tr>
    
    <tr>
        <th>
            @Html.LabelFor(model => model.Lga)
        </th>
        <td>
            <div class="labeltxt capitalize">@Model.Lga.ToLower()</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.State)
        </th>
        <td>
            <div class="labeltxt capitalize">@Model.State.ToLower()</div>
        </td>
    </tr>
    <tr>
        <th>
            @Html.LabelFor(model => model.Country)
        </th>
        <td>
            <div class="labeltxt capitalize">@Model.CountryName.ToLower()</div>
        </td>
    </tr>
</table>

EPMSEnrollmentApplication/Views/Screening/_ScreeningSearch.cshtml
@model EPMSEnrollmentApplication.Models.PassportSearch
<div class="spaced lightgray" id="searchdiv">
    <div class="leftside shadow">
        <div class="divheader">Search For Application</div>
        @using (@Html.BeginForm())
        {
            <div class="grayleftborder">
                <table>
                    <tr>
                        <th>
                            @Html.LabelFor(model => Model.FormNumber)
                        </th>
                        <td>
                            @Html.EditorFor(model => Model.FormNumber)
                            @Html.ValidationMessageFor(model => Model.FormNumber)
                        </td>
                    </tr>
                    <tr>
                        <th></th>
                        <td>
                            <div class="genbutton left spacetopm" id="GetNextScreeningbtn">Get Next Application</div>
                            <div id="searchmsg" class="searchmsg left hidden">No application found matching your search</div>
                            <div class="genbutton right spacetopm" id="SearchScreeningbtn">Search</div>
                            <div id="screeningsearchload" class="loadingdiv right">
                                <div class="smallmodal">Searching</div>
                            </div>
                            <div class="clear"></div>
                        </td>
                    </tr>
                </table>
            </div>
        }
    </div>
</div>

@if (ViewBag.Msg == "1")
{
    <script type="text/javascript">
        $(function () {
            ShowPopup("Application Accepted");
        });
    </script>
}

@if (ViewBag.Msg == "2")
{
    <script type="text/javascript">
        $(function () {
            ShowPopup("Application Rejected");
        });
    </script>
}

EPMSEnrollmentApplication/Views/Screening/_ShowPassportCompare.cshtml
@using PassportApplicationCommon.Models
@model IEnumerable<Passport>
  
  <table>
    <tr>
        <td>
            <b>Authorisation Code</b> : 12345678
        </td>
    </tr>
    <tr>
        <td>
            The first document is the one that was searched for. <br />The other passports belonging to this entity is arranged by issue date.
        </td>
    </tr>
    <tr>
        <td class="passportlist">            
            @Html.Partial("_PassportCompareheaders")
            @foreach(var pPort in Model)
            {                
                @Html.Partial("_PassportCompareColumn", pPort)
            }
        </td>
    </tr>
  </table>
  